name = "Star SMP Modpack"
author = "Gum, Fery, Ava and BitNet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cbaf76a8641cf5b6c9a7dfaeb725f9af05dff81b186780f63d9e1a271be998f7"

[versions]
fabric = "0.16.0"
minecraft = "1.20.1"
