name = "Star SMP Modpack"
author = "Gum, Fery, Ava and BitNet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "52e78c9a042ba08113252269aed1dc0d8b64a05e3812004135d33fc21579dccb"

[versions]
fabric = "0.16.0"
minecraft = "1.20.1"
